name: Send Push Notification

on:
 push:
    branches:
      - main

jobs:
 send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install web-push

      - name: Send push notification
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SUBSCRIPTION_ENDPOINT: ${{ secrets.SUBSCRIPTION_ENDPOINT }}
          P256DH_KEY: ${{ secrets.P256DH_KEY }}
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
        run: |
          const webpush = require('web-push');

          const vapidKeys = {
              publicKey: process.env.PUBLIC_KEY,
              privateKey: process.env.PRIVATE_KEY
          };

          webpush.setVapidDetails(
              'mailto:your-email@example.com',
              vapidKeys.publicKey,
              vapidKeys.privateKey
          );

          const pushSubscription = {
              endpoint: process.env.SUBSCRIPTION_ENDPOINT,
              keys: {
                 p256dh: process.env.P256DH_KEY,
                 auth: process.env.AUTH_KEY
              }
          };

          const payload = JSON.stringify({
              title: 'Nuevo precio',
              body: 'El precio de un producto ha cambiado.',
              icon: 'path/to/icon.png',
              badge: 'path/to/badge.png'
          });

          webpush.sendNotification(pushSubscription, payload).catch(error => {
              console.error(error.stack);
          });