name: MELIPU

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 requests beautifulsoup4 firebase-admin pyfcm datetime pytz
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Compile dependencies
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: MELIPU
        env:
          FIREBASE_ADMIN_SDK: ${{ secrets.FIREBASE_ADMIN_SDK }}
        run: |
          python app.py
      - name: Commit and push index.html
        run: |
          git config --global user.name 'eugeniosaintemarie'
          git config --global user.email 'e.saintemarie@outlook.com'
          git add index.html
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update index.html"
            git push https://${{ secrets.SHOP_PUBLICATIONS_AUT }}@github.com/eugeniosaintemarie/melipu.git gh-pages
          fi
